### PR TITLE
chore: increase memory and cpu requests for main and test.

### PR DESCRIPTION
**Pull request by iv1310**
Increase memory and cpu requests.
* [x] Mainnet
  * Memory: Avg usage before HPA was +/-1gb, so increase the request to 1.5gb
  * CPU: Avg usage before HPA was 0.05, so increase the requst to 0.1
* [x] Testnet
  * Memory: Avg usage before HPA was +/-700mb, so increase the request to 1gb
Screenshot_2024-03-15_16-54-23
Screenshot_2024-03-15_16-54-03
Screenshot_2024-03-15_16-53-29

### CODE REVIEW

**Comment by oap75** [comment]
Did U check the prod infra resources ? 
Make sure the scheduler can schedule the new pods based on new requests. ()specially Memory)

**Comment by iv1310** [comment]
> Did U check the prod infra resources ? Make sure the scheduler can schedule the new pods based on new requests. ()specially Memory)

Yes, that screenshot from our Infra prod

**Comment by oap75** [comment]
> Yes, that screenshot from our Infra prod

I meant about the total k8s nodes resources.

**Review by oap75 — APPROVED** [review]
Let's see what happens after merge.

**Pull request merged**
